"""customer table

Revision ID: 22694c9dd379
Revises: 99a5b0ade096
Create Date: 2023-05-15 13:18:51.641028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22694c9dd379'
down_revision = '99a5b0ade096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesperson_id'], ['sales_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
